"use client";

import { useEffect, useState } from "react";
import { ArrowRight, Check, ChevronDown, FileText, GitBranch, Info, LoaderCircle, RefreshCw, Search } from "lucide-react";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { roleLabels, scopedUsage, sumUsage, type Usage, type WorkflowAgent, type WorkflowEvent, type WorkflowSnapshot } from "@/lib/workflow";
import "./workflow.css";

const number = (n: number) => new Intl.NumberFormat("en-US").format(n);
const compact = (n: number) => n >= 1e6 ? `${(n / 1e6).toFixed(2)}M` : n >= 1e3 ? `${(n / 1e3).toFixed(1)}k` : number(n);
const percent = (n: number, d: number) => d ? `${(100 * n / d).toFixed(1)}%` : "—";
const date = (value: string) => new Date(value).toLocaleString("en-GB", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit", timeZone: "UTC" });
const time = (value: string) => new Date(value).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit", timeZone: "UTC" });
const money = (value: number | null) => value === null ? "Unavailable" : new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);
function duration(start: string, end: string) { const minutes = Math.round((Date.parse(end) - Date.parse(start)) / 60000); return `${Math.floor(minutes / 60)}h ${minutes % 60}m`; }
const descriptions: Record<string, string> = {
  coordinator: "Initialized the run, supplied market context, dispatched workers, handled shared evidence gaps and interruptions, froze artifacts, and rendered the audited report.",
  evidence: "Collected issuer filings, financial history, earnings, news and price data. Built the common evidence packet and followed up on customer-financing terms.",
  framework: "Chose common valuation methods, operating drivers, financial conventions and entry assumptions before either case was written.",
  bull: "Built the strongest defensible bullish case from the frozen evidence and framework, including counterevidence and invalidation conditions.",
  bear: "Independently built the bearish case from the same frozen evidence and framework, including cash conversion and financing stress.",
  synthesis: "Compared the completed cases, resolved modeling differences, selected a base case, and ran valuation, entry and sensitivity calculations.",
  evaluator: "Prechecked sources independently, then reviewed completed cases, calculations and synthesis against the fixed quality rubric.",
};
async function get<T>(path: string): Promise<T> { const res = await fetch(path, { cache: "no-store" }); const body = await res.json(); if (!res.ok) throw new Error(body.error ?? "Could not load workflow."); return body; }
function useLoad<T>(path: string) {
  const [result, setResult] = useState<{ path: string; data?: T; error?: string } | null>(null);
  useEffect(() => { let alive = true; get<T>(path).then(data => { if (alive) setResult({ path, data }); }).catch(error => { if (alive) setResult({ path, error: error.message }); }); return () => { alive = false; }; }, [path]);
  return result?.path === path ? result : null;
}
function Loading() { return <div className="wf-loading" role="status"><LoaderCircle className="spin" size={22} /> Loading recorded workflow…</div>; }
function Notice({ children }: { children: React.ReactNode }) { return <div className="wf-note"><Info size={16} /><div>{children}</div></div>; }
function Tokens({ usage }: { usage: Usage | null }) {
  if (!usage) return <span>Unavailable</span>;
  return <div className="wf-token-strip" aria-label={`${number(usage.cached)} cached input, ${number(usage.input - usage.cached)} uncached input, ${number(usage.output)} output tokens`}>
    <span className="wf-cached" style={{ width: `${usage.total ? usage.cached / usage.total * 100 : 0}%` }} />
    <span className="wf-fresh" style={{ width: `${usage.total ? (usage.input - usage.cached) / usage.total * 100 : 0}%` }} />
    <span className="wf-output" style={{ width: `${usage.total ? usage.output / usage.total * 100 : 0}%` }} />
  </div>;
}
function Legend() { return <div className="wf-legend"><span><i className="wf-cached" /> Cached input</span><span><i className="wf-fresh" /> Uncached input</span><span><i className="wf-output" /> Output</span></div>; }
type RunItem = { id: string; ticker: string; company: string; asOf: string; agentCount: number };
export default function WorkflowInspector() {
  const [runs, setRuns] = useState<RunItem[] | null>(null); const [run, setRun] = useState(""); const [error, setError] = useState(""); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let alive = true; get<{ items: RunItem[] }>("/api/workflows").then(({ items }) => { if (!alive) return; setRuns(items); setRun(current => current || new URLSearchParams(window.location.search).get("run") || items[0]?.id || ""); }).catch(e => { if (alive) setError(e.message); }); return () => { alive = false; }; }, []);
  function selectRun(id: string) { setRun(id); window.history.replaceState(null, "", `/workflows?run=${encodeURIComponent(id)}`); }
  return <section className="workflow-inspector">
    <header className="wf-heading"><div><h1>Research runs</h1><p>Follow the work. Understand the cost. Improve the next run.</p></div><button className="secondary-button" onClick={() => setRefresh(r => r + 1)} aria-label="Reload workflow snapshot"><RefreshCw size={16} /></button></header>
    {error ? <p role="alert">{error}</p> : !runs ? <Loading /> : !runs.length ? <div className="wf-empty"><GitBranch size={32} /><h2>Your workflow history starts here</h2><p>Import a completed run and its local session logs. No model calls are made.</p><code>npm run workflow:import -- --run reports/TICKER/TIMESTAMP --thread ROOT_THREAD_ID</code></div> : <><div className="wf-run-picker"><label htmlFor="wf-run">Research run</label><select id="wf-run" value={run} onChange={e => selectRun(e.target.value)}>{runs.map(r => <option key={r.id} value={r.id}>{r.ticker} / {r.company} / {date(r.asOf)} UTC</option>)}</select><span>Local session records</span></div>{run && <Run key={`${run}-${refresh}`} id={run} />}</>}
  </section>;
}
function Run({ id }: { id: string }) {
  const loaded = useLoad<WorkflowSnapshot>(`/api/workflows?run=${encodeURIComponent(id)}`);
  return !loaded ? <Loading /> : loaded.error ? <p role="alert">{loaded.error}</p> : <RunBody snapshot={loaded.data!} />;
}
function RunBody({ snapshot: s }: { snapshot: WorkflowSnapshot }) {
  const [scope, setScope] = useState<"research" | "session">(s.researchEndedAt ? "research" : "session");
  const [tab, setTab] = useState("workflow"); const [agentId, setAgentId] = useState(s.rootThreadId); const [artifact, setArtifact] = useState("report.md");
  const until = scope === "research" ? s.researchEndedAt : null;
  const usages = s.agents.map(a => scopedUsage(a, until)); const total = sumUsage(usages.filter((u): u is Usage => u !== null));
  const complete = usages.every(u => u !== null); const requests = s.agents.flatMap(a => a.requests).filter(r => !until || r.at <= until);
  const agent = s.agents.find(a => a.id === agentId) ?? s.agents[0]; const root = s.agents.find(a => a.id === s.rootThreadId)!;
  const rootUsage = scopedUsage(root, until);
  const rootTurns = root.turns.filter(t => !until || t.startedAt <= until);
  function openArtifact(path: string) { setArtifact(path); setTab("files"); }
  return <>
    <div className="wf-run-title"><div><span className="wf-ticker">{s.ticker}</span><div><h2>{s.company}</h2><p>Research cutoff {date(s.asOf)} UTC</p></div></div><div className="wf-scope" aria-label="Usage scope"><button aria-pressed={scope === "research"} disabled={!s.researchEndedAt} onClick={() => setScope("research")}>Research only</button><button aria-pressed={scope === "session"} onClick={() => setScope("session")}>Entire task</button></div></div>
    <div className="wf-metrics">
      <div><span>{complete ? "Recorded tokens" : "Known tokens · incomplete"}</span><strong title={number(total.total)}>{compact(total.total)}</strong><small>{number(total.total)} across {requests.length} responses</small></div>
      <div><span>Cached share of input</span><strong>{percent(total.cached, total.input)}</strong><small>{compact(total.input - total.cached)} uncached input + {compact(total.output)} output</small></div>
      <div><span>Agents in this run</span><strong>{s.agents.length}<em> / {rootTurns.length} attempts</em></strong><small>Coordinator + {s.agents.length - 1} workers; attempts refer to coordinator</small></div>
      <div><span>Saved quality audit</span><strong>{s.audit ? s.audit.score : "—"}<em> / 100</em></strong><small>{s.audit?.status === "pass" ? "Passed" : s.audit?.status ?? "Not available"} · {s.audit?.findings.filter(f => f.status === "open").length ?? 0} open findings</small></div>
    </div>
    <div className="wf-scope-note"><span>{scope === "research" ? "Through first completed research response" : "Includes research, import and later explanations"} · {date(s.startedAt)} – {date(until ?? s.endedAt)} UTC</span><span>{duration(s.startedAt, until ?? s.endedAt)} elapsed, including pauses</span></div>
    <nav className="wf-tabs" aria-label="Workflow sections">{[["workflow", "Agent workflow"], ["timeline", "Time & retries"], ["usage", "Token usage"], ["results", "Results & quality"], ["files", `Artifacts (${s.artifacts.length})`]].map(([id,label]) => <button key={id} aria-current={tab === id ? "page" : undefined} onClick={() => setTab(id)}>{label}</button>)}</nav>
    {tab === "workflow" && <>
      <div className="wf-section-heading"><div><h3>From evidence to judgment</h3><p>Select an agent to inspect its work. Connections show artifact handoffs; elapsed time is in the turn ledger.</p></div><span className="wf-status"><Check size={13} /> Recorded run</span></div>
      <div className="wf-map">
        <button className={`wf-coordinator ${agentId === root.id ? "is-selected" : ""}`} onClick={() => setAgentId(root.id)} aria-pressed={agentId === root.id}><span><GitBranch size={19} /><strong>Coordinator</strong><span>Dispatch, shared gaps, retries & delivery</span></span><span><strong>{rootUsage ? compact(rootUsage.total) : "Unknown"}</strong><span>{rootUsage ? percent(rootUsage.total, total.total) : "—"} of recorded tokens</span></span></button>
        <div className="wf-flow">{["evidence", "framework", "cases", "synthesis", "evaluator"].map((role,index) => <div className="wf-flow-step" key={role}><div className={role === "cases" ? "wf-pair" : ""}>{(role === "cases" ? ["bull","bear"] : [role]).map(r => { const a = s.agents.find(a => a.role === r); if (!a) return <span key={r}>No {r} record</span>; const u = scopedUsage(a,until); return <button key={r} className={`wf-agent-node wf-role-${r} ${agentId === a.id ? "is-selected" : ""}`} onClick={() => setAgentId(a.id)} aria-pressed={agentId === a.id}><span className="wf-node-stage">{role === "cases" ? "Independent case" : ["Collect","Define","","Compare","Audit"][index]}</span><strong>{r === "bull" ? "Bull analyst" : r === "bear" ? "Bear analyst" : r === "evaluator" ? "Evaluator" : r === "evidence" ? "Evidence" : r === "framework" ? "Framework" : "Synthesis"}</strong><span className="wf-node-usage">{u ? compact(u.total) : "Unknown"} <small>tokens</small></span></button>; })}</div>{index < 4 && <ArrowRight className="wf-flow-arrow" size={18} aria-hidden />}</div>)}</div>
        <div className="wf-map-caption"><span><GitBranch size={14} /> Bull and bear used separate fresh contexts with the same frozen inputs.</span><span>Evaluator precheck began before synthesis; final review followed completed artifacts.</span></div>
      </div>
      <AgentDetail key={agent.id} agent={agent} snapshot={s} until={until} openArtifact={openArtifact} />
    </>}
    {tab === "timeline" && <Timeline snapshot={s} until={until} onAgent={id => { setAgentId(id); setTab("workflow"); }} />}
    {tab === "usage" && <UsageView snapshot={s} total={total} until={until} onAgent={id => { setAgentId(id); setTab("workflow"); }} />}
    {tab === "results" && <Results snapshot={s} openArtifact={openArtifact} />}
    {tab === "files" && <Artifacts snapshot={s} selected={artifact} onSelect={setArtifact} />}
    <details className="wf-method"><summary><Info size={15} /> How this was measured <ChevronDown size={14} /></summary><ul>{s.notes.map(n => <li key={n}>{n}</li>)}</ul><p>Snapshot captured {date(s.capturedAt)} UTC. {s.researchBoundary}</p><p>Re-import the same run to refresh this snapshot. Reloading this page does not read new session logs or run models.</p></details>
  </>;
}
function AgentDetail({ agent: a, snapshot: s, until, openArtifact }: { agent: WorkflowAgent; snapshot: WorkflowSnapshot; until: string | null; openArtifact: (path: string) => void }) {
  const [tab, setTab] = useState("overview"); const u = scopedUsage(a,until); const turns = a.turns.filter(t => !until || t.startedAt <= until);
  return <section className="wf-detail" aria-label="Selected agent">
    <div className="wf-detail-heading"><div><span className="wf-agent-path">{a.path}</span><h3>{roleLabels[a.role] ?? a.role}</h3></div><div className="wf-model">{a.model}<span>{a.effort} reasoning effort</span></div></div>
    <nav className="wf-subtabs" aria-label="Agent detail sections">{[["overview","Overview"],["events","Actions & inputs / outputs"],["turns","Turn ledger"]].map(([key,label]) => <button key={key} aria-current={tab === key ? "page" : undefined} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {tab === "overview" ? <div className="wf-agent-overview"><div><p className="wf-agent-description">{descriptions[a.role] ?? "Recorded worker in this research run."}</p><div className="wf-boundaries"><div><h4>Recorded inputs</h4><ul>{a.inputs.map(x => <li key={x}>{x}</li>)}</ul></div><div><h4>Recorded outputs</h4><ul>{a.outputs.map(x => <li key={x}>{s.artifacts.some(f => f.path === x) ? <button className="wf-file-link" onClick={() => openArtifact(x)}><FileText size={13} />{x}</button> : x}</li>)}</ul></div></div>{a.restrictions.length > 0 && <details className="wf-restrictions"><summary>Input restrictions</summary><ul>{a.restrictions.map(r => <li key={r}>{r}</li>)}</ul></details>}<p className="wf-muted">{a.parentId ? "Input and output lists come from the saved dispatch record." : "Coordinator boundaries are summarized from the saved workflow record."} These describe assigned boundaries, not proof of every file read.</p></div><aside className="wf-agent-usage"><h4>Agent usage</h4><strong>{u ? number(u.total) : "Unavailable"}</strong><span>recorded tokens</span><Tokens usage={u} /><dl><dt>Cached input</dt><dd>{u ? number(u.cached) : "—"}</dd><dt>Uncached input</dt><dd>{u ? number(u.input-u.cached) : "—"}</dd><dt>Output</dt><dd>{u ? number(u.output) : "—"}</dd><dt>Reasoning within output</dt><dd>{u ? number(u.reasoning) : "—"}</dd><dt>Recorded interruptions</dt><dd>{turns.filter(t => t.status === "interrupted").length}</dd></dl><p>{a.usageSource}. Reasoning is a subset of output.</p>{a.warnings.map(w => <p className="wf-warning" key={w}>{w}</p>)}</aside></div> : tab === "events" ? <Events key={`${a.id}-${until}`} runId={s.id} agentId={a.id} until={until} /> : <TurnLedger agent={a} until={until} />}
  </section>;
}
function Events({ runId, agentId, until }: { runId: string; agentId: string; until: string | null }) {
  const result = useLoad<{ events: WorkflowEvent[] }>(`/api/workflows?run=${encodeURIComponent(runId)}&agent=${encodeURIComponent(agentId)}`);
  const [query, setQuery] = useState(""); const [kind, setKind] = useState("all"); const [limit, setLimit] = useState(40);
  const events = (result?.data?.events ?? []).filter(e => (!until || e.at <= until) && (kind === "all" || e.kind === kind) && `${e.title} ${e.input ?? ""} ${e.output ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="wf-events"><Notice>Inspect public messages, commands, tool inputs and outputs. Encrypted handoff text is marked unavailable. Private reasoning is not part of this view.</Notice><div className="wf-event-controls"><label className="wf-search"><Search size={16} /><input aria-label="Search agent activity" placeholder="Search commands, files, messages…" value={query} onChange={e => {setQuery(e.target.value);setLimit(40);}} /></label><select aria-label="Filter activity type" value={kind} onChange={e => {setKind(e.target.value);setLimit(40);}}>{["all","tool","command","handoff","input","message","error"].map(k => <option key={k} value={k}>{k === "all" ? "All activity" : k}</option>)}</select><span>{events.length} events</span></div>{!result ? <Loading /> : result.error ? <p role="alert">{result.error}</p> : <>{events.slice(0,limit).map(e => <details className={`wf-event ${e.kind === "error" ? "wf-event-error" : ""}`} key={e.id}><summary><time>{time(e.at)}</time><span className="wf-event-kind">{e.kind}</span><strong>{e.title}</strong><ChevronDown size={14} /></summary><div className="wf-event-body"><p className="wf-muted">{date(e.at)} UTC {e.status ? ` / ${e.status}` : ""}</p>{e.unavailable && <Notice>{e.unavailable}</Notice>}{e.input && <><h4>Input</h4><pre>{e.input}</pre></>}{e.output && <><h4>Output</h4><pre>{e.output}</pre></>}{!e.output && e.kind === "tool" && <p className="wf-muted">No textual output recorded for this call.</p>}</div></details>)}{!events.length && <p className="wf-muted">No matching recorded activity.</p>}{events.length > limit && <button className="secondary-button wf-more" onClick={() => setLimit(n => n + 40)}>Show 40 more events</button>}</>}</div>;
}
function TurnLedger({ agent, until }: { agent: WorkflowAgent; until: string | null }) {
  const turns = agent.turns.filter(t => !until || t.startedAt <= until);
  return <div className="wf-ledger"><p className="wf-muted">One entry per invocation or continuation. Interruption counts are per agent; parallel failures can come from the same account limit.</p>{turns.map((t,i) => { const u = sumUsage(agent.requests.filter(r => r.turnId === t.id && (!until || r.at <= until))); return <details key={t.id} className="wf-turn"><summary><span className="wf-turn-index">{i+1}</span><div><strong>{t.input?.trim().slice(0,100) || (i ? "Follow-up / continuation" : "Initial assignment")}</strong><span>{date(t.startedAt)} – {t.endedAt ? date(t.endedAt) : "unfinished"} UTC</span></div><span className={`wf-turn-state ${t.status}`}>{t.status}</span><b>{compact(u.total)}</b><ChevronDown size={14} /></summary><div>{t.error && <Notice>{t.error}</Notice>}{t.input && <><h4>User input</h4><pre>{t.input}</pre></>}{t.result && <><h4>Final response</h4><pre>{t.result}</pre></>}{!t.input && <p>The assignment is recorded as an agent handoff. Exact encrypted text is unavailable.</p>}<small>{t.id}</small></div></details>; })}</div>;
}
function UsageView({ snapshot: s, total, until, onAgent }: { snapshot: WorkflowSnapshot; total: Usage; until: string | null; onAgent: (id: string) => void }) {
  const [metric,setMetric] = useState<"total"|"uncached">("total");
  const rows = s.agents.map(a => ({ a, u: scopedUsage(a,until) })).sort((a,b) => (b.u?.total ?? 0)-(a.u?.total ?? 0));
  const root = s.agents.find(a => a.id === s.rootThreadId)!; const waits = root.requests.filter(r => (!until || r.at <= until) && r.action === "collaboration.wait_agent");
  const plotted = s.agents.flatMap(a => a.requests).filter(r => !until || r.at <= until).sort((a,b) => a.at.localeCompare(b.at));
  const points = plotted.reduce<{ index: number; amount: number }[]>((all, r, index) => [...all, { index, amount: (all.at(-1)?.amount ?? 0) + (metric === "total" ? r.total : r.input-r.cached+r.output) }], []);
  const max = points.at(-1)?.amount || 1;
  return <div className="wf-usage-view"><div className="wf-section-heading"><div><h3>Where the tokens went</h3><p>Context is counted again on every model response. Cached input is included in total input.</p></div><Legend /></div><div className="wf-usage-table-wrap"><table className="wf-usage-table"><thead><tr><th>Agent</th><th>Total tokens</th><th>Share</th><th>Cached input</th><th>Uncached input</th><th>Output</th><th>Responses</th></tr></thead><tbody>{rows.map(({a,u}) => <tr key={a.id}><td><button onClick={() => onAgent(a.id)}>{roleLabels[a.role] ?? a.role}</button><Tokens usage={u}/></td><td>{u ? number(u.total) : "Unknown"}</td><td>{u ? percent(u.total,total.total) : "—"}</td><td>{u ? number(u.cached) : "—"}</td><td>{u ? number(u.input-u.cached) : "—"}</td><td>{u ? number(u.output) : "—"}</td><td>{a.requests.filter(r => !until || r.at <= until).length}</td></tr>)}</tbody><tfoot><tr><th>Recorded total</th><td>{number(total.total)}</td><td>100%</td><td>{number(total.cached)}</td><td>{number(total.input-total.cached)}</td><td>{number(total.output)}</td><td>{plotted.length}</td></tr></tfoot></table></div>
    <div className="wf-usage-bottom"><section className="wf-chart-panel"><div className="wf-section-heading"><div><h3>Cumulative tokens</h3><p>Response order across all agents; idle periods are compressed.</p></div><select aria-label="Cumulative chart metric" value={metric} onChange={e => setMetric(e.target.value as "total"|"uncached")}><option value="total">All tokens</option><option value="uncached">Uncached input + output</option></select></div><div className="wf-chart"><span>{compact(max)}</span><svg viewBox="0 0 600 180" role="img" aria-label={`Cumulative ${metric === "total" ? "total" : "uncached input plus output"} tokens across ${plotted.length} responses, ending at ${number(max)}`}><path d="M0 179 H600 M0 90 H600 M0 1 H600" fill="none" stroke="#dce3ec" strokeDasharray="3 5" /><polyline points={`0,179 ${points.map(p => `${((p.index+1)/Math.max(points.length,1))*600},${179-p.amount/max*178}`).join(" ")}`} fill="none" stroke="#3158ad" strokeWidth="2.5" /></svg><div><span>First response</span><span>Response {plotted.length}</span></div></div></section><section className="wf-observations"><h3>What to improve first</h3><p><strong>Keep the coordinator’s context smaller.</strong> It accounts for {percent(scopedUsage(root,until)?.total ?? 0,total.total)} of tokens. Pass compact receipts and artifact paths instead of repeatedly loading full files.</p><p><strong>Reduce status-loop responses.</strong> {waits.length} responses issuing wait calls account for {compact(sumUsage(waits).total)} tokens. This is model context usage associated with those responses, not a charge for waiting.</p><p><strong>Measure before changing models.</strong> Preserve independent cases and the quality gate. Compare a versioned workflow against this baseline before claiming savings.</p></section></div>
    <Notice><strong>Token counts do not translate directly to subscription allowances.</strong> The logs show {root.turns.filter(t => t.status === "interrupted" && (!until || t.startedAt <= until)).length} coordinator usage-limit interruptions in this scope. The five-hour quota is account-wide; no dollar cost or exact allowance attribution is available here. These observations do not verify five full allowances consumed by this task alone.</Notice>
    <details className="wf-requests"><summary>Inspect individual response counts ({plotted.length})</summary><div className="wf-table-scroll"><table className="wf-usage-table"><thead><tr><th>Time (UTC)</th><th>Agent / recorded response action</th><th>Input</th><th>Cached subset</th><th>Output</th><th>Total</th></tr></thead><tbody>{plotted.map(r => <tr key={r.id}><td>{date(r.at)}</td><td><span className="wf-response-agent">{s.agents.find(a => a.requests.some(x => x.id === r.id))?.role}</span>{r.action}</td><td>{number(r.input)}</td><td>{number(r.cached)}</td><td>{number(r.output)}</td><td>{number(r.total)}</td></tr>)}</tbody></table></div></details>
  </div>;
}
function Timeline({ snapshot: s, until, onAgent }: { snapshot: WorkflowSnapshot; until: string | null; onAgent: (id: string) => void }) {
  const start = Date.parse(s.startedAt), end = Date.parse(until ?? s.endedAt), span = Math.max(1, end-start);
  const turns = s.agents.flatMap(a => a.turns.filter(t => !until || t.startedAt <= until).map(t => ({a,t}))).sort((a,b) => a.t.startedAt.localeCompare(b.t.startedAt));
  return <div className="wf-timeline-view"><div className="wf-section-heading"><div><h3>Work, interruptions and continuations</h3><p>Actual wall-clock time in UTC. Bars show invocation intervals, including tool waits; blank space is time between invocations.</p></div><span className="wf-status">{duration(s.startedAt,until ?? s.endedAt)} elapsed</span></div>
    <div className="wf-timeline-scroll"><div className="wf-timeline"><div className="wf-timeline-axis"><span>Agent</span><div>{[0,.25,.5,.75,1].map(n => <span key={n} style={{left:`${n*100}%`}}>{date(new Date(start+n*span).toISOString())}</span>)}</div></div>{s.agents.map(a => <div className="wf-timeline-row" key={a.id}><button onClick={() => onAgent(a.id)}>{roleLabels[a.role] ?? a.role}</button><div className="wf-time-track">{a.turns.filter(t => !until || t.startedAt <= until).map((t,i) => { const turnEnd = Math.min(end,Date.parse(t.endedAt ?? s.endedAt)); return <button key={t.id} className={`wf-time-bar ${t.status}`} style={{left:`${Math.max(0,(Date.parse(t.startedAt)-start)/span)*100}%`,width:`${Math.max(0,(turnEnd-Date.parse(t.startedAt))/span)*100}%`}} onClick={() => onAgent(a.id)} aria-label={`${a.role}, attempt ${i+1}, ${t.status}, ${date(t.startedAt)} to ${t.endedAt ? date(t.endedAt) : "unfinished"} UTC`} title={`${a.role} / attempt ${i+1} / ${t.status}\n${date(t.startedAt)} – ${t.endedAt ? date(t.endedAt) : "unfinished"} UTC`} />; })}</div></div>)}</div></div><div className="wf-time-legend"><span><i /> Completed invocation</span><span><i className="interrupted" /> Ended in interruption</span><span>Very short invocations have a minimum 3 px marker.</span></div>
    <div className="wf-section-heading"><div><h3>Invocation ledger</h3><p>Select an agent for recorded input boundaries, accessible actions and final responses.</p></div></div><div className="wf-usage-table-wrap"><table className="wf-usage-table"><thead><tr><th>Started (UTC)</th><th>Agent</th><th>Result</th><th>Invocation elapsed</th><th>Tokens</th></tr></thead><tbody>{turns.map(({a,t}) => <tr key={t.id}><td>{date(t.startedAt)}</td><td><button onClick={() => onAgent(a.id)}>{roleLabels[a.role] ?? a.role}</button></td><td><span className={`wf-turn-state ${t.status}`}>{t.status}</span></td><td>{t.endedAt ? duration(t.startedAt,t.endedAt) : "Unfinished"}</td><td>{a.usage ? number(sumUsage(a.requests.filter(r => r.turnId === t.id && (!until || r.at <= until))).total) : "Unknown"}</td></tr>)}</tbody></table></div>
  </div>;
}
function Results({ snapshot: s, openArtifact }: { snapshot: WorkflowSnapshot; openArtifact: (path: string) => void }) {
  return <div className="wf-results"><div className="wf-section-heading"><div><h3>The saved research result</h3><p>Original conclusions at the research cutoff; no new stock research was run.</p></div><button className="secondary-button" onClick={() => openArtifact("report.md")}><FileText size={15} /> Read full report</button></div>{s.result && <section className="wf-verdict"><span className="wf-verdict-label">{s.result.conclusion}</span><h3>At a recorded market price of {money(s.result.marketPrice)}</h3><p>{s.result.summary}</p><div className="wf-table-scroll"><table className="wf-usage-table"><thead><tr><th>Scenario</th><th>Fair value today</th><th>12-month price</th><th>Total return</th><th>Entry ceiling</th></tr></thead><tbody>{s.result.scenarios.map(r => <tr key={r.name}><th>{r.name}</th><td>{money(r.fairValue)}</td><td>{money(r.horizonValue)}</td><td>{r.totalReturn === null ? "—" : `${(r.totalReturn*100).toFixed(1)}%`}</td><td>{money(r.entry)}</td></tr>)}</tbody></table></div></section>}
    <div className="wf-quality-grid"><section><h3>Independent audit</h3><p className="wf-muted">{s.audit?.score ?? "—"}/100 under the saved rubric. This measures research quality, not investment success.</p>{s.audit?.dimensions.map(d => <div className="wf-dimension" key={d.id}><span>{d.name}<small>{d.weight}% weight</small></span><meter min={0} max={4} value={d.score} aria-label={d.name} /><strong>{d.score}/4</strong></div>)}<button className="wf-file-link" onClick={() => openArtifact("audit-notes.md")}>Read audit notes <ArrowRight size={14} /></button></section><section><h3>Evidence coverage</h3><p className="wf-muted">{s.evidence?.claims ?? "—"} claims from {s.evidence?.sources ?? "—"} sources</p>{s.evidence?.coverage.map(c => <details key={c.area} className="wf-coverage"><summary><span>{c.area}</span><b>{c.status}</b><ChevronDown size={14} /></summary><p>{c.notes}</p></details>)}</section></div>
    <section className="wf-findings"><h3>Open audit findings</h3>{s.audit?.findings.map(f => <article key={f.id}><span>{f.severity} / {f.status}</span><p>{f.description}</p><p><strong>Suggested correction:</strong> {f.remediation}</p></article>)}</section>
  </div>;
}
function Artifacts({ snapshot: s, selected, onSelect }: { snapshot: WorkflowSnapshot; selected: string; onSelect: (path: string) => void }) {
  const [query,setQuery] = useState(""); const artifacts = s.artifacts.filter(a => a.path.toLowerCase().includes(query.toLowerCase()));
  return <div className="wf-artifacts"><aside><label className="wf-search"><Search size={15} /><input aria-label="Search artifacts" placeholder="Find a file…" value={query} onChange={e => setQuery(e.target.value)} /></label><p className="wf-muted">{artifacts.length} files · original run</p><nav aria-label="Run artifacts">{artifacts.map(a => <button key={a.path} aria-current={selected === a.path ? "page" : undefined} onClick={() => onSelect(a.path)}><FileText size={14}/><span>{a.path}<small>{number(a.bytes)} bytes{!a.readable ? " · metadata only" : ""}</small></span></button>)}</nav></aside><Artifact key={selected} snapshot={s} path={selected} /></div>;
}
function Artifact({ snapshot, path }: { snapshot: WorkflowSnapshot; path: string }) {
  const info = snapshot.artifacts.find(a => a.path === path);
  return !info ? <p>Select an artifact.</p> : !info.readable ? <section className="wf-artifact-preview"><h3>{path}</h3><Notice>This file is preserved in the original run. Text preview supports files up to 3 MB.</Notice><code>{info.hash}</code></section> : <ArtifactText snapshot={snapshot} path={path} />;
}
function ArtifactText({ snapshot, path }: { snapshot: WorkflowSnapshot; path: string }) {
  const result = useLoad<{ path: string; text: string; hash: string; matchesSnapshot: boolean }>(`/api/workflows?run=${encodeURIComponent(snapshot.id)}&artifact=${encodeURIComponent(path)}`);
  const [raw, setRaw] = useState(false); const data = result?.data;
  return <section className="wf-artifact-preview"><div className="wf-artifact-heading"><h3>{path}</h3>{path.endsWith(".md") && <button className="secondary-button" aria-pressed={raw} onClick={() => setRaw(!raw)}>{raw ? "Read document" : "View raw"}</button>}</div>{!result ? <Loading /> : result.error ? <p role="alert">{result.error}</p> : data && <><p className={`wf-integrity ${data.matchesSnapshot ? "" : "wf-warning"}`}>{data.matchesSnapshot ? <Check size={14} /> : <Info size={14}/>} {data.matchesSnapshot ? "Matches captured SHA-256" : "Changed since snapshot; re-import to refresh"}</p>{path.endsWith(".md") && !raw ? <div className="markdown-document wf-markdown"><Markdown remarkPlugins={[remarkGfm]} skipHtml urlTransform={url => /^https?:\/\//i.test(url) ? url : ""} components={{ a: ({href,children}) => href ? <a href={href} target="_blank" rel="noopener noreferrer">{children}</a> : <span>{children}</span>, img: () => null, table: ({children}) => <div className="markdown-table-scroll"><table>{children}</table></div> }}>{data.text}</Markdown></div> : <pre className="wf-artifact-code">{data.text}</pre>}</>}</section>;
}
